### ISSUE TITLE
Issue switching to any realm besides NA

### ISSUE THREAD

**Issue by rushing01** [shupershuff/Diablo2RLoader#29]
Using parameters, every time i try to log on to EU or AS, it will say this account is locked due to suspicious activity. I have to go and get security code for email. I dont have MFA on any of these accounts. Have no issues running them on NA server. Did I miss something?

**Comment by shupershuff** [comment]
I've not personally experienced this, although I have heard of others bring up this issue.
Have you tried launching from BNet to each of those regions?
Are you using a VPN?

**Comment by rushing01** [comment]
Yes i tried launching in each region from bnet and it works, but as soon as I try in loader i get same error. It will only show offline and if you click online you get that notice about being locked. I am not using VPN. Using Windows 11. It won't even let me connect to them using tokens either

**Comment by shupershuff** [comment]
Hey there. 
There shouldn't be any difference from launching via script with Token vs launching via Battlenet as they both use the same method of authentication. I would only expect issues with the token method if the PW has been changed or if MFA has been enabled/disabled as these actions may render the token invalid (requiring it to be setup again).

Have you had much luck in the last few days? This issue seems to resolve itself from others that have mentioned it to me.

**Comment by rushing01** [comment]
nope no luck, I even left them in EU for a few hours to see if that was the issue, but it always goes into offline mode on EU or Asia. Works perfectly fine on NA.

**Comment by shupershuff** [comment]
What happens when you try connecting with shortcuts to EU (instructions [here](https://github.com/shupershuff/D2r-Multiboxing-Without-A-Script#launch-via-parameters-with-a-desktop-shortcut)).
Note that this method will not work with KR as it's still down.

If you still have issues, perhaps try resetting your password.

**Comment by rushing01** [comment]
it does the same thing, goes into offline mode if i try connecting to EU. Works just fine using NA. I don't know if im doing something wrong or my pc just hates me.

**Comment by shupershuff** [comment]
That's really odd. I won't be able to help you though sorry as the issue lies with your accounts.
Maybe try resetting your password (as I think that email suggests) and if issues persist, contact Blizzard for support on why your account keeps getting marked as suspicious.

Obviously if you've used a VPN to authenticate at any point, connect from various locations or have given your account credentials out to someone else, this will cause these issues.

**Comment by rushing01** [comment]
only thing i can think of is im using a new computer on these accounts but have played on all of them already before using this loader

**Comment by shupershuff** [comment]
I know this issue is annoying for you but I'm going to close this issue off as it's not something that I or this script can assist with further. 
I would suggest resetting your passwords, only logging in from one network location and from one computer. 
I'm not sure how well tokens will work if reused on another computer so I would redo that too.

If issues persist, you could look at deleting your user config files (in the saved game folder) and start fresh.
Another thing to try is [deleting cookie.bin](https://us.forums.blizzard.com/en/d2r/t/cannot-enter-the-game-because-i-was-30-days-offline/113482/6).

If none of that helps, you may be best to go to Blizzard forums to troubleshoot why your account keeps nagging you.

**Comment by Skillossus** [comment]
@rushing01 Did you ever get this resolved? Having the same thing happen to my 3 accounts and it's infuriating...

**Comment by shupershuff** [comment]
Do your passwords have any special characters in it? If so maybe try one without asterix "*", comma ",", dash "-" or question mark "?".

**Comment by Skillossus** [comment]
Hey thanks for responding,

No, nothing like that just a-z 0-9.
Would constantly get this error if I switched regions whilst logged in via -username and -password arguments to d2r.exe
![1700509797-D2R](https://github.com/shupershuff/Diablo2RLoader/assets/151090282/555663c3-e581-47ca-91d5-6d335e142929)

I ended up avoiding this issue but via the use of web tokens and the registry but what was here was a little too fancy for my purposes so I stared from scratch https://gist.github.com/Skillossus/e65aacb6388fa570e2df86611441cad5
