### ISSUE TITLE
Is this out of date?

### ISSUE THREAD

**Issue by KurtCocain** [shupershuff/Diablo2RLoader#38]
It does open all 3 accounts but none of them can connect to bnet once opened. just hands on "connecting to battlenet"

**Comment by shupershuff** [comment]
Still works, I've been using it each day. Sounds like either your password is incorrect, MFA enabled on one or more of accounts or your accounts need attention security wise.
When you log into the accounts via the website do you get any security prompts?

Please note, if you change the password in accounts.csv you need to ensure the column "PasswordIsSecureString" is blank so the script knows to secure the password.
If the account is MFA enabled then you can connect using token authentication instead (see readme for instructions on setup).

**Comment by ismail986081** [comment]
I got the similar issue. It cannot connect any longer and then the error "you have not been online for 30 days" pops up.
It worked smooth until the last patch.

**Comment by shupershuff** [comment]
> I got the similar issue. It cannot connect any longer and then the error "you have not been online for 30 days" pops up. It worked smoothly until the last patch.

This isn't an issue with the launcher. There are many, many posts about that error online.
If you can get in fine with the battlenet launcher but not my launcher, then odds are you've entered your credentials incorrectly or you're trying to launch an MFA enabled account using a password instead of a token (refer to account setup instructions).
