### ISSUE TITLE
[Feature Request] Add setting to skip 'press any key to continue'

### ISSUE THREAD

**Issue by mrhappyasthma** [shupershuff/Diablo2RLoader#49]
After connecting a new char or issuing a command that prints info, it would be nice to automatically go back to main menu. The 'press any key to continue' is actually a bit annoying.

Not sure if that is done manually in the script or as a result of running a sub-process.

**Comment by shupershuff** [comment]
If you can you please elaborate where exactly you're seeing this, I can either explain why there is a forced pause or assess whether it's still needed.

**Comment by mrhappyasthma** [comment]
![image](https://github.com/user-attachments/assets/89b1712b-93d6-4631-b205-409fe078f3c0)

Will this go away if I disable this somehow in the config?

**Comment by mrhappyasthma** [comment]
Ah yes there is a setting for this! I missed it.

**Comment by shupershuff** [comment]
> ![image](https://private-user-images.githubusercontent.com/1547356/363461190-89b1712b-93d6-4631-b205-409fe078f3c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzgyMDEsIm5iZiI6MTcyNTE3NzkwMSwicGF0aCI6Ii8xNTQ3MzU2LzM2MzQ2MTE5MC04OWIxNzEyYi05M2Q2LTQ2MzEtYjIwNS00MDlmZTA3OGYzYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDgwNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg1ZmY5NGNjYzVlMTE5YzgyZmYwNThiOGY4ZjA4YmM1NzQ3MDI1ZWIxODQ4ZDM5OTA5ZmQwYzIzMjJjNDBmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RYYvzVjjZ5zz8WUscR2GLAqUt22byympC_QLFsinBrU)
> 
> Will this go away if I disable this somehow in the config?

This will go away once you've configured the account to work with that feature or disable the feature.
I needed to let users know that if they have the feature enabled, they actually have to configure where they want the window to be for that account. Rather than get them to guess coordinates I made it so they can move their window(s) to preferred locations and then save coordinates via the options menu (as per the steps).

I'm open to better wording if the instructions aren't clear.
