### ISSUE TITLE
Discord push to talk seems to get captured by window

### ISSUE THREAD

**Issue by acr-gaming** [shupershuff/Diablo2RLoader#5]
I think this is due to the D2R instance running in admin mode? Starting discord in admin mode doesn't seem to fix. I *think* starting D2r in non-admin would fix but have not tested.

I have tested launching regularly through launcher does fix it.

I believe the actual launched instances of d2r don't need to be admin? Just the script itself. I assume they are inheriting admin mode from the script...

**Comment by shupershuff** [comment]
Thanks for letting me know.
Have reproduced the issue, will see what I can do.

**Comment by shupershuff** [comment]
A quick update to note I haven't forgotten about this, still something I want to resolve but it's proving tricky.

**Comment by shupershuff** [comment]
Good news and bad news, let's start with the bad...

**Bad News:** 
Without implementing something crazy/cumbersome it doesn't appear there's an easy way of running non-elevated processes from an elevated PowerShell Context. I also don't believe I can make the script run properly without Admin rights as the window renamer at the very least requires elevation to work.

**Good News:**
Thankfully you can get around this issue by running Discord in Administrator mode:

[https://support.discord.com/hc/en-us/articles/205082178-How-do-I-enable-push-to-talk-if-I-am-running-my-game-in-administrator-mode](https://support.discord.com/hc/en-us/articles/205082178-How-do-I-enable-push-to-talk-if-I-am-running-my-game-in-administrator-mode-)

Recommend you find the Discord Shortcut or app, go into properties > Compatibility and check the box for "Run this program as administrator" so that it always runs as admin.  :)
