### ISSUE TITLE
request: add additional command line arguments

### ISSUE THREAD

**Issue by andygami** [shupershuff/Diablo2RLoader#9]
i use mods coz i use mosaic sin so i dont get blinded. and loot filter too. would be a great feature!

**Comment by shupershuff** [comment]
I have added this today in my working draft of the next release. I have added an option in config.xml to add in additional CMD parameters so that you don't have to edit the script directly.

Perhaps you can test for me before I publish? :D
I've updated D2Loader.ps1 in the repository if you'd like to try it (it should automatically add the missing config.xml option after you run it once)

**Comment by shupershuff** [comment]
This will be in the next release
